// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// The property tables: the enumerated and binary properties, scripts and
// their extensions, and the bidi mirroring and bracket data.

#include "munigen.h"

static const char* const s_graphemeBreakNames[] = {
    "XX", "CR", "LF", "CN", "EX", "ZWJ", "RI", "PP", "SM", "L", "V", "T", "LV", "LVT",
};
static const char* const s_wordBreakNames[] = {
    "XX", "CR", "LF", "NL", "Extend", "ZWJ", "RI", "FO", "KA",        "HL",
    "LE", "SQ", "DQ", "MB", "ML",     "MN",  "NU", "EX", "WSegSpace",
};
static const char* const s_sentenceBreakNames[] = {
    "XX", "CR", "LF", "EX", "SE", "FO", "SP", "LO", "UP", "LE", "NU", "AT", "SC", "ST", "CL",
};
static const char* const s_indicConjunctBreakNames[] = {
    "None",
    "Linker",
    "Consonant",
    "Extend",
};

static const char* const s_lineBreakNames[] = {
    "XX", "BK", "CR", "LF", "CM", "NL", "SG", "WJ", "ZW", "GL", "SP", "ZWJ", "B2",
    "BA", "BB", "HY", "CB", "CL", "CP", "EX", "IN", "NS", "OP", "QU", "IS",  "NU",
    "PO", "PR", "SY", "AI", "AL", "CJ", "EB", "EM", "H2", "H3", "HL", "ID",  "JL",
    "JV", "JT", "RI", "SA", "AK", "AP", "AS", "VF", "VI", "HH",
};
static const char* const s_eastAsianWidthNames[] = {"N", "A", "H", "W", "F", "Na"};
static const char* const s_bidiClassNames[] = {
    "L",  "R",  "AL",  "EN",  "ES",  "ET",  "AN",  "CS",  "NSM", "BN",  "B",   "S",
    "WS", "ON", "LRE", "LRO", "RLE", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI",
};

// Canonical_Combining_Class, field 3 of UnicodeData.txt, stored as is.
static void LoadCombiningClass(uint8_t* values)
{
    FILE* file = OpenUcd("UnicodeData.txt");
    char line[MAX_LINE];
    memset(values, 0, CODE_POINTS);
    while (fgets(line, sizeof(line), file) != nullptr)
    {
        char* fields[15];
        if (SplitFields(line, fields, 15) < 4 || fields[0][0] == '\0')
        {
            continue;
        }
        long value = strtol(fields[3], nullptr, 10);
        if (value < 0 || value > 254)
        {
            Fail("bad combining class '%s' in UnicodeData.txt", fields[3]);
        }
        values[ParseCodePoint(fields[0], "UnicodeData.txt")] = (uint8_t)value;
    }
    fclose(file);
}

// Writes the ISO 15924 tag of every script index into src/generated/,
// big-endian ASCII in a uint32_t ('Latn' is 0x4C61746E). The indexes from
// 252 up are left free: the security checks number the writing systems
// Hanb, Hntl, Jpan and Kore there.
static void WriteScriptTags(char names[][8], int count)
{
    if (count > 252)
    {
        Fail("%d scripts leave no room for the writing systems", count);
    }
    FILE* file = CreateOutput("script_tags.c");
    fprintf(file, "// SPDX-License-Identifier: MIT\n// Copyright (c) 2026 Sirac Ozmen\n//\n");
    fprintf(file, "// The ISO 15924 tag of each Script value the Script table stores.\n");
    fprintf(file, "// Generated by tools/munigen from PropertyValueAliases.txt in tools/ucd/\n");
    fprintf(file, "// (Unicode 18.0.0); do not edit.\n// clang-format off\n\n");
    fprintf(file, "#include \"../tables.h\"\n\n");
    fprintf(file, "const uint32_t muniScriptTags[%d] = {", count);
    for (int i = 0; i < count; i++)
    {
        if (strlen(names[i]) != 4)
        {
            Fail("script '%s' has no four-letter tag", names[i]);
        }
        uint32_t tag = (uint32_t)(unsigned char)names[i][0] << 24 |
                       (uint32_t)(unsigned char)names[i][1] << 16 |
                       (uint32_t)(unsigned char)names[i][2] << 8 |
                       (uint32_t)(unsigned char)names[i][3];
        fprintf(file, "\n    0x%08Xu, // %s", tag, names[i]);
    }
    fprintf(file, "\n};\n\nconst uint16_t muniScriptTagCount = %d;\n", count);
    fclose(file);
}

// Script_Extensions from ScriptExtensions.txt. The table stores, for each
// code point, 0 when its extensions are just its Script, or 1 plus the
// index of its set among the distinct sets, each a list of Script
// indexes in the order the file gives them.
#define MAX_SETS    255
#define MAX_MEMBERS 4096

typedef struct ScriptSets
{
    int count;
    int starts[MAX_SETS + 1];
    uint8_t members[MAX_MEMBERS];
} ScriptSets;

// The index of a set of members in sets, adding it when it is new.
static int SetIndex(ScriptSets* sets, const uint8_t* members, int size)
{
    for (int i = 0; i < sets->count; i++)
    {
        int start = sets->starts[i];
        if (sets->starts[i + 1] - start == size &&
            memcmp(sets->members + start, members, (size_t)size) == 0)
        {
            return i;
        }
    }
    int start = sets->starts[sets->count];
    if (sets->count == MAX_SETS || start + size > MAX_MEMBERS)
    {
        Fail("ScriptExtensions.txt: too many sets");
    }
    memcpy(sets->members + start, members, (size_t)size);
    sets->count += 1;
    sets->starts[sets->count] = start + size;
    return sets->count - 1;
}

static void LoadScriptExtensions(uint8_t* values, const char* const* scripts, int scriptCount,
                                 ScriptSets* sets)
{
    FILE* file = OpenUcd("ScriptExtensions.txt");
    char line[MAX_LINE];
    memset(values, 0, CODE_POINTS);
    sets->count = 0;
    sets->starts[0] = 0;
    while (fgets(line, sizeof(line), file) != nullptr)
    {
        char* fields[3];
        if (line[0] == '#' || line[0] == '\n' || SplitFields(line, fields, 3) < 2)
        {
            continue;
        }
        uint32_t first;
        uint32_t last;
        ParseRange(fields[0], &first, &last, "ScriptExtensions.txt");
        uint8_t members[64];
        int size = 0;
        for (char* name = strtok(fields[1], " "); name != nullptr; name = strtok(nullptr, " "))
        {
            if (size == 64)
            {
                Fail("ScriptExtensions.txt: a set of more than 64 scripts");
            }
            members[size++] = ValueIndex(scripts, scriptCount, name, "ScriptExtensions.txt");
        }
        memset(values + first, SetIndex(sets, members, size) + 1, last - first + 1);
    }
    fclose(file);
}

static void WriteScriptSets(const ScriptSets* sets)
{
    FILE* file = CreateOutput("script_sets.c");
    fprintf(file, "// SPDX-License-Identifier: MIT\n// Copyright (c) 2026 Sirac Ozmen\n//\n");
    fprintf(file, "// The distinct Script_Extensions sets: set i holds the Script indexes\n");
    fprintf(file, "// muniScriptSetMembers[muniScriptSetStarts[i]] up to the start of set\n");
    fprintf(file, "// i + 1. Generated by tools/munigen from ScriptExtensions.txt in\n");
    fprintf(file, "// tools/ucd/ (Unicode 18.0.0); do not edit.\n// clang-format off\n\n");
    fprintf(file, "#include \"../tables.h\"\n\n");
    fprintf(file, "const uint16_t muniScriptSetStarts[%d] = {", sets->count + 1);
    for (int i = 0; i <= sets->count; i++)
    {
        fprintf(file, "%s%d,", i % 12 == 0 ? "\n    " : " ", sets->starts[i]);
    }
    fprintf(file, "\n};\n\nconst uint8_t muniScriptSetMembers[%d] = {", sets->starts[sets->count]);
    for (int i = 0; i < sets->starts[sets->count]; i++)
    {
        fprintf(file, "%s%d,", i % 16 == 0 ? "\n    " : " ", sets->members[i]);
    }
    fprintf(file, "\n};\n");
    fclose(file);
}

// Bidi_Mirroring_Glyph from BidiMirroring.txt. The table stores, for
// each code point, 0 when it has no mirror, or 1 plus the index of the
// distance to its mirror in deltas, a list of the distinct distances in
// order of first use.
#define MAX_DELTAS 255

static int LoadMirroring(uint8_t* values, int32_t* deltas)
{
    FILE* file = OpenUcd("BidiMirroring.txt");
    char line[MAX_LINE];
    int count = 0;
    memset(values, 0, CODE_POINTS);
    while (fgets(line, sizeof(line), file) != nullptr)
    {
        char* fields[3];
        if (line[0] == '#' || line[0] == '\n' || SplitFields(line, fields, 3) < 2)
        {
            continue;
        }
        uint32_t codePoint = ParseCodePoint(fields[0], "BidiMirroring.txt");
        int32_t delta =
            (int32_t)ParseCodePoint(fields[1], "BidiMirroring.txt") - (int32_t)codePoint;
        int index = 0;
        while (index < count && deltas[index] != delta)
        {
            index++;
        }
        if (index == count)
        {
            if (count == MAX_DELTAS)
            {
                Fail("BidiMirroring.txt: more than %d distinct distances", MAX_DELTAS);
            }
            deltas[count++] = delta;
        }
        values[codePoint] = (uint8_t)(index + 1);
    }
    fclose(file);
    return count;
}

static void WriteMirrorDeltas(const int32_t* deltas, int count)
{
    FILE* file = CreateOutput("bidi_mirror_deltas.c");
    fprintf(file, "// SPDX-License-Identifier: MIT\n// Copyright (c) 2026 Sirac Ozmen\n//\n");
    fprintf(file, "// The distances from code points to their Bidi_Mirroring_Glyph; the\n");
    fprintf(file, "// BidiMirror table stores 1 plus an index into them. Generated by\n");
    fprintf(file, "// tools/munigen from BidiMirroring.txt in tools/ucd/ (Unicode 18.0.0);\n");
    fprintf(file, "// do not edit.\n// clang-format off\n\n");
    fprintf(file, "#include \"../tables.h\"\n\n");
    fprintf(file, "const int32_t muniBidiMirrorDeltas[%d] = {", count);
    for (int i = 0; i < count; i++)
    {
        fprintf(file, "%s%d,", i % 10 == 0 ? "\n    " : " ", deltas[i]);
    }
    fprintf(file, "\n};\n");
    fclose(file);
}

// Bidi_Paired_Bracket_Type from BidiBrackets.txt: 0 none, 1 open, 2
// close. The file's Bidi_Paired_Bracket must be the Bidi_Mirroring_Glyph,
// which the library then uses for both.
static void LoadBrackets(uint8_t* values, const uint8_t* mirrors, const int32_t* deltas)
{
    FILE* file = OpenUcd("BidiBrackets.txt");
    char line[MAX_LINE];
    memset(values, 0, CODE_POINTS);
    while (fgets(line, sizeof(line), file) != nullptr)
    {
        char* fields[4];
        if (line[0] == '#' || line[0] == '\n' || SplitFields(line, fields, 4) < 3)
        {
            continue;
        }
        uint32_t codePoint = ParseCodePoint(fields[0], "BidiBrackets.txt");
        uint32_t pair = ParseCodePoint(fields[1], "BidiBrackets.txt");
        if (mirrors[codePoint] == 0 ||
            (uint32_t)((int32_t)codePoint + deltas[mirrors[codePoint] - 1]) != pair)
        {
            Fail("BidiBrackets.txt: U+%04X pairs with U+%04X, not its mirror", codePoint, pair);
        }
        values[codePoint] = strcmp(fields[2], "o") == 0 ? 1 : strcmp(fields[2], "c") == 0 ? 2 : 0;
    }
    fclose(file);
}

// General_Category from UnicodeData.txt. Ranges appear as a "<..., First>"
// line followed by its "<..., Last>" line; code points the file does not
// list are unassigned (Cn, value 0).
static const char* const s_generalCategoryNames[] = {
    "Cn", "Lu", "Ll", "Lt", "Lm", "Lo", "Mn", "Mc", "Me", "Nd", "Nl", "No", "Pc", "Pd", "Ps",
    "Pe", "Pi", "Pf", "Po", "Sm", "Sc", "Sk", "So", "Zs", "Zl", "Zp", "Cc", "Cf", "Cs", "Co",
};

static void LoadGeneralCategory(uint8_t* values)
{
    FILE* file = OpenUcd("UnicodeData.txt");
    char line[MAX_LINE];
    uint32_t rangeFirst = 0;
    int inRange = 0;
    int nameCount = COUNT_OF(s_generalCategoryNames);
    while (fgets(line, sizeof(line), file) != nullptr)
    {
        char* fields[15];
        if (SplitFields(line, fields, 15) < 3 || fields[0][0] == '\0')
        {
            continue;
        }
        uint32_t codePoint = ParseCodePoint(fields[0], "UnicodeData.txt");
        uint8_t value = ValueIndex(s_generalCategoryNames, nameCount, fields[2], "UnicodeData.txt");
        size_t nameLength = strlen(fields[1]);
        if (nameLength > 8 && strcmp(fields[1] + nameLength - 8, ", First>") == 0)
        {
            rangeFirst = codePoint;
            inRange = 1;
            continue;
        }
        uint32_t first = inRange ? rangeFirst : codePoint;
        for (uint32_t c = first; c <= codePoint; c++)
        {
            values[c] = value;
        }
        inRange = 0;
    }
    fclose(file);
}

// The identifier properties (UAX #31) as bits: 1 XID_Start,
// 2 XID_Continue, 4 Pattern_Syntax, 8 Pattern_White_Space.
static void WriteIdentifier(uint8_t* values)
{
    static const struct
    {
        const char* file;
        const char* name;
    } s_bits[4] = {
        {"DerivedCoreProperties.txt", "XID_Start"},
        {"DerivedCoreProperties.txt", "XID_Continue"},
        {"PropList.txt", "Pattern_Syntax"},
        {"PropList.txt", "Pattern_White_Space"},
    };
    uint8_t* bits = Allocate(CODE_POINTS);
    for (int bit = 0; bit < 4; bit++)
    {
        LoadBinary(s_bits[bit].file, s_bits[bit].name, values);
        for (uint32_t c = 0; c < CODE_POINTS; c++)
        {
            bits[c] |= (uint8_t)(values[c] << bit);
        }
    }
    WriteTable(bits, "identifier", "Identifier", "Identifier properties",
               "DerivedCoreProperties.txt and PropList.txt");
    free(bits);
}

// The emoji properties of UTS #51 as bits, in the order src/tables.h
// gives them: Extended_Pictographic, which segmentation reads, first.
static void WriteEmoji(uint8_t* values)
{
    static const char* const names[6] = {
        "Extended_Pictographic", "Emoji",           "Emoji_Presentation", "Emoji_Modifier",
        "Emoji_Modifier_Base",   "Emoji_Component",
    };
    uint8_t* bits = Allocate(CODE_POINTS);
    for (int bit = 0; bit < 6; bit++)
    {
        LoadBinary("emoji-data.txt", names[bit], values);
        for (uint32_t c = 0; c < CODE_POINTS; c++)
        {
            bits[c] |= (uint8_t)(values[c] << bit);
        }
    }
    WriteTable(bits, "emoji", "Emoji", "Emoji properties", "emoji-data.txt");
    free(bits);
}

// The zeros of the decimal digit systems (General_Category Nd), sorted.
// A digit's value is its distance from the greatest zero at or below it,
// which the generator checks for every digit.
static void WriteDecimalZeros(void)
{
    uint32_t zeros[128];
    int count = 0;
    FILE* input = OpenUcd("UnicodeData.txt");
    char line[MAX_LINE];
    while (fgets(line, sizeof(line), input) != nullptr)
    {
        char* fields[15];
        if (SplitFields(line, fields, 15) < 7 || strcmp(fields[2], "Nd") != 0)
        {
            continue;
        }
        uint32_t codePoint = ParseCodePoint(fields[0], "UnicodeData.txt");
        uint32_t value = (uint32_t)strtoul(fields[6], nullptr, 10);
        if (value == 0 && count == COUNT_OF(zeros))
        {
            Fail("more than %d decimal digit systems", COUNT_OF(zeros));
        }
        if (value == 0)
        {
            zeros[count++] = codePoint;
        }
        else if (count == 0 || zeros[count - 1] != codePoint - value || value > 9)
        {
            Fail("U+%04X: its zero is not the greatest zero before it", codePoint);
        }
    }
    fclose(input);
    FILE* file = CreateOutput("decimal_zeros.c");
    fprintf(file, "// SPDX-License-Identifier: MIT\n// Copyright (c) 2026 Sirac Ozmen\n//\n");
    WriteComment(file, "The zeros of the decimal digit systems: see src/tables.h. Generated by "
                       "tools/munigen from UnicodeData.txt in tools/ucd/ (Unicode 18.0.0); do "
                       "not edit.");
    fprintf(file, "// clang-format off\n\n#include \"../tables.h\"\n\n");
    fprintf(file, "const uint32_t muniDecimalZeros[%d] = {", count);
    for (int i = 0; i < count; i++)
    {
        fprintf(file, "%s0x%05X,", i % 8 == 0 ? "\n    " : " ", zeros[i]);
    }
    fprintf(file, "\n};\n\nconst uint16_t muniDecimalZeroCount = %d;\n", count);
    fclose(file);
    printf("%-24s %7d bytes  %d systems\n", "DecimalZeros", count * 4 + 2, count);
}

void WriteProperties(void)
{
    uint8_t* values = Allocate(CODE_POINTS);

    LoadGeneralCategory(values);
    WriteTable(values, "general_category", "GeneralCategory", "General_Category",
               "UnicodeData.txt");
    LoadEnumerated("GraphemeBreakProperty.txt", "GCB", nullptr, s_graphemeBreakNames,
                   COUNT_OF(s_graphemeBreakNames), values);
    WriteTable(values, "grapheme_cluster_break", "GraphemeClusterBreak", "Grapheme_Cluster_Break",
               "GraphemeBreakProperty.txt");
    LoadEnumerated("WordBreakProperty.txt", "WB", nullptr, s_wordBreakNames,
                   COUNT_OF(s_wordBreakNames), values);
    WriteTable(values, "word_break", "WordBreak", "Word_Break", "WordBreakProperty.txt");
    LoadEnumerated("SentenceBreakProperty.txt", "SB", nullptr, s_sentenceBreakNames,
                   COUNT_OF(s_sentenceBreakNames), values);
    WriteTable(values, "sentence_break", "SentenceBreak", "Sentence_Break",
               "SentenceBreakProperty.txt");
    LoadEnumerated("DerivedCoreProperties.txt", "InCB", "InCB", s_indicConjunctBreakNames,
                   COUNT_OF(s_indicConjunctBreakNames), values);
    WriteTable(values, "indic_conjunct_break", "IndicConjunctBreak", "Indic_Conjunct_Break",
               "DerivedCoreProperties.txt");
    WriteEmoji(values);
    LoadBinary("PropList.txt", "White_Space", values);
    WriteTable(values, "white_space", "WhiteSpace", "White_Space", "PropList.txt");
    WriteDecimalZeros();
    LoadEnumerated("LineBreak.txt", "lb", nullptr, s_lineBreakNames, COUNT_OF(s_lineBreakNames),
                   values);
    WriteTable(values, "line_break", "LineBreak", "Line_Break", "LineBreak.txt");
    LoadEnumerated("EastAsianWidth.txt", "ea", nullptr, s_eastAsianWidthNames,
                   COUNT_OF(s_eastAsianWidthNames), values);
    WriteTable(values, "east_asian_width", "EastAsianWidth", "East_Asian_Width",
               "EastAsianWidth.txt");
    LoadEnumerated("DerivedBidiClass.txt", "bc", nullptr, s_bidiClassNames,
                   COUNT_OF(s_bidiClassNames), values);
    WriteTable(values, "bidi_class", "BidiClass", "Bidi_Class", "DerivedBidiClass.txt");
    LoadCombiningClass(values);
    WriteTable(values, "canonical_combining_class", "CombiningClass", "Canonical_Combining_Class",
               "UnicodeData.txt");
    static char scriptNames[256][8];
    int scriptCount = AllShortNames("sc", scriptNames, 256);
    const char* scriptList[256];
    for (int i = 0; i < scriptCount; i++)
    {
        scriptList[i] = scriptNames[i];
    }
    LoadEnumerated("Scripts.txt", "sc", nullptr, scriptList, scriptCount, values);
    WriteTable(values, "script", "Script", "Script", "Scripts.txt");
    WriteScriptTags(scriptNames, scriptCount);
    WriteIdentifier(values);
    static ScriptSets scriptSets;
    LoadScriptExtensions(values, scriptList, scriptCount, &scriptSets);
    WriteTable(values, "script_extensions", "ScriptExtensions", "Script_Extensions sets",
               "ScriptExtensions.txt");
    WriteScriptSets(&scriptSets);
    static int32_t deltas[MAX_DELTAS];
    int deltaCount = LoadMirroring(values, deltas);
    WriteTable(values, "bidi_mirror", "BidiMirror", "Bidi_Mirroring_Glyph distances",
               "BidiMirroring.txt");
    WriteMirrorDeltas(deltas, deltaCount);
    uint8_t* mirrors = Allocate(CODE_POINTS);
    memcpy(mirrors, values, CODE_POINTS);
    LoadBrackets(values, mirrors, deltas);
    free(mirrors);
    WriteTable(values, "bidi_bracket", "BidiBracket", "Bidi_Paired_Bracket_Type",
               "BidiBrackets.txt");

    free(values);
}
